// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "barkinator.h"

static Fl_Round_Button *osc1_type_sawtooth=(Fl_Round_Button *)0;

static Fl_Round_Button *osc1_type_square=(Fl_Round_Button *)0;

static Fl_Slider *osc1_inA=(Fl_Slider *)0;

static Fl_Slider *osc1_inB=(Fl_Slider *)0;

static Fl_Slider *osc1_inC=(Fl_Slider *)0;

Fl_Double_Window* make_window() {
    Fl_Double_Window* w = new Fl_Double_Window(350, 595, "Window");
    Fl_Group* osc1_group = new Fl_Group(25, 25, 300, 200, "Oscillator 1");
    osc1_group->box(FL_THIN_UP_BOX);
    osc1_group->labelfont(1);

    osc1_type_sawtooth = new Fl_Round_Button(45, 40, 25, 25, "sawtooth");
    osc1_type_sawtooth->type(102);
    osc1_type_sawtooth->down_box(FL_ROUND_DOWN_BOX);

    osc1_type_square = new Fl_Round_Button(140, 40, 25, 25, "square");
    osc1_type_square->type(102);
    osc1_type_square->down_box(FL_ROUND_DOWN_BOX);

    Fl_Spinner* osc1_frequency = new Fl_Spinner(125, 70, 60, 25, "Frequency ");
    osc1_frequency->value(30);

    osc1_inA = new Fl_Slider(60, 110, 256, 25, "A");
    osc1_inA->type(1);
    osc1_inA->minimum(1);
    osc1_inA->maximum(256);
    osc1_inA->step(1);
    osc1_inA->value(10);
    osc1_inA->align(Fl_Align(FL_ALIGN_LEFT));

    osc1_inB = new Fl_Slider(60, 150, 256, 25, "B");
    osc1_inB->type(1);
    osc1_inB->minimum(1);
    osc1_inB->maximum(256);
    osc1_inB->step(1);
    osc1_inB->value(10);
    osc1_inB->align(Fl_Align(FL_ALIGN_LEFT));

    osc1_inC = new Fl_Slider(60, 190, 256, 25, "C");
    osc1_inC->type(1);
    osc1_inC->minimum(1);
    osc1_inC->maximum(256);
    osc1_inC->step(1);
    osc1_inC->value(10);
    osc1_inC->align(Fl_Align(FL_ALIGN_LEFT));

    w->end();
    w->size_range(300, 300, 1000, 1000);
    w->end();

    return w;
}
