// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef barkinator_h
#define barkinator_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Slider.H>
extern "C" { Fl_Double_Window* make_window(); }
#endif
